

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.0.100/orderingfood?characterEncoding=utf-8&useSSL=false
#  jpa:
#    show-sql: true
server:
  servlet:
    context-path: /orderingfood
logging:
  pattern:
    console: "%d - %msg%n"
  file:
      path: D:/Program Files/IT/DATA/idae/localhost/StudyProject/orderingfood-sell/log/tomcat/
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.orderingfood.pojo